system SuddenCraven
{
    technique 
    {
        material                                mp_flare_04
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       3
            angle                               0
            time_to_live                        0.75
            velocity                            500
            particle_width                      250
            particle_height                     250
            emits                               emitter_particle Flare
            force_emission                      true
        }
        emitter                                 Point Flare
        {
            time_to_live                        dyn_random
            {
                min                             0.2
                max                             0.5
            }
            particle_width                      250
            particle_height                     250
        }
        affector                                Colour Affector1
        {
            time_colour                         0    0.501961 0 0.501961 0.6
            time_colour                         0.493478  0.639216 0.639216 0.639216 0.309804
            time_colour                         1    0.501961 0 1 0.6
        }
        affector                                TextureRotator Affector117
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      dyn_random
            {
                min                             -15
                max                             15
            }
        }
        observer                                OnClear Observer19
        {
            observe_until_event                 true
            handler                             DoStopSystem Handler19
            {
            }
        }
    }
}
