system FireSummoning
{
  scale 0.075 0.075 0.075
    keep_local                                  true
    technique
    {
        position                                0 0 0
        visual_particle_quota                   3
        material                                mp_seal_04
        default_particle_width                  400
        default_particle_height                 400
        renderer                                Billboard
        {
            billboard_type                      perpendicular_self
            billboard_rotation_type             vertex
            common_direction                    0 1 0
            common_up_vector                    0 0 1
            render_queue_group                  20
        }
        emitter                                 Point
        {
            emission_rate                       15
            angle                               0
            time_to_live                        2
            velocity                            0.0001
            duration                            0.3
            colour                              1 0.501961 0.25098 1
        }
        affector                                Colour
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.5  1 1 1 1
            time_colour                         1    0 0 0 1
            colour_operation                    multiply
        }
        observer                                OnTime
        {
            observe_until_event                 true
            handler                             DoStopSystem
            {
            }
            since_start_system                  true
            on_time                             greater_than 3
        }
    }
    technique
    {
        position                                0 0 0
        visual_particle_quota                   400
        emitted_emitter_quota                   100
        material                                mp_fire_02
        renderer                                Billboard
        {
            texture_coords_rows                 2
            texture_coords_columns              2
            render_queue_group                  80
            billboard_rotation_type vertex
        }
        emitter                                 Circle CircleEmitter
        {
            emission_rate                       50
            angle                               0
            velocity                            20
            position                            0 400 0
            direction                           0 -1 0
            emits                               emitter_particle PointEmitter
            force_emission                      true
            radius                              150
            step                                0.4
            emit_random                         false
            normal                              0 1 0
        }
        emitter                                 SphereSurface PointEmitter
        {
            emission_rate                       100
            angle                               0
            time_to_live                        dyn_random
            {
                min                             0.5
                max                             1
            }
            velocity                            0
            duration                            2
            all_particle_dimensions             dyn_random
            {
                min                             80
                max                             120
            }
            direction                           0 -1 0
            colour                              0 0 0 1
        }
        affector                                Scale
        {
        }
        affector                                Colour
        {
            time_colour                         0    0 0 0 1
            time_colour                         0.45  1 0.501961 0.25098 1
            time_colour                         1    0 0 0 1
        }
        affector                                Vortex Affector24
        {
            rotation_axis                       0 1 0
            rotation_speed                      10
        }
        affector                                TextureRotator Affector84
        {
            rotation                            dyn_random
            {
                min                             -180
                max                             180
            }
            rotation_speed                      0
        }
    }
}
