system Elementum/Fx/CometExplosion
{
    scale 0.4 0.4 0.4
  velocity_scale 0.4 0.4 0.4
    technique
    {
        visual_particle_quota                   250
        material                                mp_flare_04
        renderer                                Billboard
        {
        }
        emitter                                 Box
        {
            emission_rate                       500
            time_to_live                        dyn_random
            {
                min                             1
                max                             2
            }
            velocity                            dyn_random
            {
                min                             500
                max                             2000
            }
            all_particle_dimensions             dyn_random
            {
                min                             40
                max                             200
            }
            colour                              0.184314 0.184314 1 1
            box_height                          1
        }
        affector                                LinearForce Affector336
        {
            force_vector                        0 -3500 0
        }
        affector                                Scale Affector383
        {
            xyz_scale                           dyn_random
            {
                min                             500
                max                             2000
            }
        }
        affector                                TextureRotator Affector384
        {
            rotation                            dyn_random
            {
                min                             -3
                max                             3
            }
            rotation_speed                      7
        }
        observer                                OnTime Observer55
        {
            observe_until_event                 true
            handler                             DoStopSystem Handler57
            {
            }
            since_start_system                  true
            on_time                             greater_than 1.5
        }
    }
}
