system KissOfDeath
{
  scale 0.1 0.1 0.1
    technique
    {
        material                                PUMediaPack/Snow_01
        renderer                                Billboard
        {
            billboard_rotation_type             vertex
            render_queue_group                  80
        }
        emitter                                 Point
        {
            emission_rate                       250
            angle                               5
            time_to_live                        dyn_random
            {
                min                             0.4
                max                             0.7
            }
            velocity                            150
            duration                            1
            direction                           0 0 1
            position 0 150 50
        }
        affector                                Scale Affector167
        {
            xyz_scale                           dyn_random
            {
                min                             200
                max                             400
            }
        }
        affector                                Colour Affector166
        {
            time_colour                         0    0.501961 0 0 0.294118
            time_colour                         0.495652  0 0 0 0.207843
            time_colour                         1    0.501961 0 0 0.294118
        }
        affector                                TextureRotator Affector168
        {
            rotation                            dyn_random
            {
                min                             0
                max                             360
            }
        }
        observer                                OnClear Observer10
        {
            observe_until_event                 true
            handler                             DoStopSystem Handler11
            {
            }
        }
    }
}
